services:
  server-logiflowerp-configuracion:
    container_name: server-logiflowerp-configuracion
    image: logiflowerp/server-logiflowerp-configuracion:latest
    env_file:
     - .env
    environment:
      NODE_ENV: production
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
