export const SHARED_TYPES = {
    AdapterMongoDB: Symbol.for('AdapterMongoDB'),
    AdapterToken: Symbol.for('AdapterToken'),
    AdapterSocket: Symbol.for('AdapterSocket'),
    AdapterRedis: Symbol.for('AdapterRedis'),
    AdapterMail: Symbol.for('AdapterMail'),
    AdapterApiRequest: Symbol.for('AdapterApiRequest'),
    AdapterRabbitMQ: Symbol.for('AdapterRabbitMQ'),
    database_logiflow: Symbol.for('database_logiflow'),
    collection_users: Symbol.for('collection_users'),
    collection_endpoints: Symbol.for('collection_endpoints'),
    collection_systemOptions: Symbol.for('collection_systemOptions'),
    collection_productPrices: Symbol.for('collection_productPrices'),
    collection_currencies: Symbol.for('collection_currencies'),
    collection_profiles: Symbol.for('collection_profiles'),
    UseCaseSendMailRegisterUser: Symbol.for('UseCaseSendMailRegisterUser'),
}